name: blind_nav
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

ddependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.3.8
  geolocator: ^10.1.0  # ğŸ—ºï¸ Added for GPS location access # ğŸ”Š Added for voice feedback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
dependencies:
  flutter_tts: ^4.2.3
  geolocator: ^14.0.2
